### ISSUE TITLE
Bad request on unsupported formality

### ISSUE THREAD

**Issue by mattbrannon** [DeepLcom/deepl-node#1]
Currently, a request that specifies a formality setting not yet supported by DeepL returns an error without a translation. 
`DeepLError: Bad request, message: 'formality' is not supported for given 'target_lang'.`

Maybe a more user friendly alternative would be to just ignore any unsupported options in the request, possibly attaching a warning message to the response informing the user of their mistake. This way, applications that call the DeepL api won't break when supplied an invalid configuration.

**Comment by TasseDeCafe** [comment]
I just want to add my support for this feature, it would be easier to set up the requests that way.

**Comment by daniel-jones-deepl** [comment]
Hello again, we've added two new allowed formality values: `prefer_less` and `prefer_more`. They have the same function as `less` and `more` if the target language supports formality. Otherwise they fallback to the `default` formality, and you will not get the error mentioned above.
