### ISSUE TITLE
Is it possible to get the alternatives of the phrase as well ?

### ISSUE THREAD

**Issue by serhanguney** [DeepLcom/deepl-node#11]
When using the translator in the website we are able to get alternatives along with the translated phrase. For example I'm translating the word `friend` into Czech language and I'm getting the following result:

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/67260021/196423357-55f6baac-75c0-4b8f-b1ae-e91b45bfb2de.png">

When using `deepl-node` API I'm only getting a single string in return which seems to be the original translation. Is it possible to get a translation response including these alternatives ? If not, why not ?

Thanks

**Comment by daniel-jones-deepl** [comment]
Hi @serhanguney, thanks for creating this issue, sorry that I took so long to reply.

No, for business reasons the API does not provide the alternative translations.
