### ISSUE TITLE
[QUESTION] Temporary glosseries

### ISSUE THREAD

**Issue by busybox11** [DeepLcom/deepl-node#18]
This is not really an issue, but rather a question, and possibly feature request.
Would it be possible to have some kind of temporary glossaries, that you could pass as an argument in a translate request, without having to create a glossary?

To give a more precise example, here is my use case:

I am building a translation tool that would allow automatically translating strings from one language to a bunch of other languages.
Those strings may contain parameters (something like `The count is [count].`).
Sometimes, the translation result will rightly place the parameter like a word in a sentence, keeping its original form.
Sometimes it will also translate the parameter's name.
I would like to keep the original parameter name, without creating a glossary that would hold values on your side, when I only need them once.

This is admittedly much more complex than just a stipped-down glossary feature, but that would already be a start.

I hope you were able to understand my thoughts and hope this is somewhat usable feedback, but I am completly aware of its complexity and would not be surprised if it never finds its way onto future updates.

Also I apologize for my english if you didn't understand everything, I'm not a native speaker and I try not to use Deepl but to talk by myself as much as I can (ironically haha).

**Comment by JanEbbing** [comment]
Hi @busybox11 , thanks for your interest in the Library!
I believe we support what you request under the name of [XML tag handling](https://www.deepl.com/docs-api/xml/), see also [HTML handling](https://www.deepl.com/docs-api/html/).
For this you would need to convert your placeholders to XML.
In the python library, we also have an [example](https://github.com/DeepLcom/deepl-python/tree/main/examples/mustache) how to write something like this for the Mustache templating language.

Please let me know if this doesn't support your use case!
