### ISSUE TITLE
Uncaught TypeError: os.type is not a function

### ISSUE THREAD

**Issue by alandolsi** [DeepLcom/deepl-node#31]
I become this error when i initialise the repository

Uncaught TypeError: os.type is not a function
    at Translator.constructUserAgentString (deepl-node.js?v=e2e7fb1a:3446:33)
    at new Translator (deepl-node.js?v=e2e7fb1a:3116:30)
    at main.js:8:20
constructUserAgentString @ deepl-node.js?v=e2e7fb1a:3446
Translator @ deepl-node.js?v=e2e7fb1a:3116
(anonym) @ main.js:8

**Comment by JanEbbing** [comment]
Hi, which version of NodeJS are you using? Are you using some kind of framework to build an application with (React Native, Ionic, etc)? It seems the `os` [module](https://nodejs.org/api/os.html#ostype) of Node isn't available.

I will create a task anyway to make sure an exception in that function doesn't break the library.

**Comment by JanEbbing** [comment]
Hi @alandolsi .

1. To fix the direct error you are seeing, you need to polyfill the `os` module as [Vite does not](https://vitejs.dev/guide/troubleshooting.html#others). There are some people with similar problems and their solutions [here](https://stackoverflow.com/questions/69286329/polyfill-node-os-module-with-vite-rollup-js), [here](https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2) and [this is a module which does this](https://www.npmjs.com/package/vite-plugin-node-polyfills).
2. However, this is a NodeJS package and the above is a bandaid solution. Please read [this answer](https://support.deepl.com/hc/en-us/articles/7869276014748-API-request-blocked-by-CORS-policy-) why we don't support running in the frontend (I think this is the next problem you would run into, aside from likely leaking your API key in the frontend source code). You will need some backend that can make the DeepL API requests.

Please let me know if this doesn't solve your problem.
