### ISSUE TITLE
feature: translate a text to multiple Languages

### ISSUE THREAD

**Issue by idirbfs** [DeepLcom/deepl-node#35]
Hello,
Is there a way to translate a text to multiple languages?
like this: 
`Translator.translateText(text, null, targetLangs as deepl.TargetLanguageCode[]);`

**Comment by JanEbbing** [comment]
Hi, you would need to make multiple `translateText` calls to get the result in different languages.

```javascript
const results = await Promise.all(targetLangs.map((targetLang) => Translator.translateText(text, null, targetLang)));
```

**Comment by idirbfs** [comment]
thank you!
