### ISSUE TITLE
Docs: `createGlossaryFromCsv` should be `createGlossaryWithCsv`

### ISSUE THREAD

**Issue by phenomen** [DeepLcom/deepl-node#36]
https://github.com/DeepLcom/deepl-node/blob/45032d54e3297b60b7b829c6a5fa4f26de9b37d8/README.md?plain=1#L257C1-L269C1

`createGlossaryFromCsv` method does not exist in `deepl-node` but there is `createGlossaryWithCsv` instead.

**Comment by daniel-jones-deepl** [comment]
Thanks for the report @phenomen, I'll fix this.
