### ISSUE TITLE
Update axios to latest version

### ISSUE THREAD

**Issue by suharelli** [DeepLcom/deepl-node#40]
Version used by deepl-node has vulnerabilities and should be updated

- moderate | Follow Redirects improperly handles URLs in the url.parse() function 
- Package  | follow-redirects 
-  Patched in | >=1.15.4 
- Dependency of | deepl-node 
- Path | deepl-node > axios > follow-redirects 
- More info | https://www.npmjs.com/advisories/1095374

**Comment by daniel-jones-dev** [comment]
Hi @suharelli, thanks for the report. I'll look into it.

**Comment by daniel-jones-dev** [comment]
Fixed in [v1.11.1](https://github.com/DeepLcom/deepl-node/releases/tag/v1.11.1).
