### ISSUE TITLE
'ar' missing from CommonLanguageCode type

### ISSUE THREAD

**Issue by admehta01** [DeepLcom/deepl-node#41]
https://github.com/DeepLcom/deepl-node/blob/main/src/types.ts#L168 is missing 'ar' which is [supported by DeepL](https://www.deepl.com/docs-api/translate-text/translate-text).

**Comment by JanEbbing** [comment]
This is released in v1.2.0, which is already on npm

**Comment by admehta01** [comment]
Do you mean v1.12.0 (published a day ago)?

**Comment by JanEbbing** [comment]
Yes, sorry for the typo
