### ISSUE TITLE
Does this package work with webpack?

### ISSUE THREAD

**Issue by AhnafS** [DeepLcom/deepl-node#5]
I'm trying to implement this package while using webpack, and each time there always seems to be a new problem. Is it just not possible to use deepl-node with webpack?

**Comment by mattbrannon** [comment]
@AhnafS It would probably be helpful if you explained a bit more about what exactly you're trying to do. That being said, more than likely you're issue is with Webpack rather than DeepL.

**Comment by daniel-jones-deepl** [comment]
Hi @AhnafS, thanks for the question.

We haven't tested the package with webpack. I do not know your application, but I want to note: this package is not intended for frontend applications.
