### ISSUE TITLE
The API doesn't translate English to Spanish when there's a small typo; it just returns the English text. However, it works for English to French.

### ISSUE THREAD

**Issue by JavaPr288** [DeepLcom/deepl-node#50]
**Describe the bug**
I try to translate Hello darkness my old friend Ive come to talk with you again to Spanish gives Hello darkness my old friend Ive come to talk with you again.
However with French and Italian it works correctly

**To Reproduce**
Use the API To Translate English to Spanish 
Hello darkness my old friend Ive come to talk with you again to Spanish gives Hello darkness my old friend Ive come to talk with you again.

**Expected behavior**
It should translate to Spanish

Timestamp: 2024-06-25 22:15:42

**Error Spanish**
![image](https://github.com/DeepLcom/deepl-node/assets/78695000/40d1bd73-e7d3-40a4-aa27-a6ba6363b720)

**Correct Spanish No Typo**
![image](https://github.com/DeepLcom/deepl-node/assets/78695000/e1517ba1-a04f-4c5a-b1a1-5766346c0fce)

**Working French**
![image](https://github.com/DeepLcom/deepl-node/assets/78695000/9c008068-fe3d-4da9-a947-a0baf7a0e7bf)

**Comment by JanEbbing** [comment]
I cant reproduce this (using our python CLI to hit the API):

```
$ poetry run python -m deepl text --to "ES" "Hello darkness my old friend Ive come to talk with you again"

Hola oscuridad mi viejo amigo he venido a hablar con usted otra vez
```

**Comment by JavaPr288** [comment]
Hi,
I realized I was using a context prompt which was correct the problem when I removed the prompt it got resolved.

Thanks for your help!
```
async function translateText(text, targetLang) {
  try {
    const systemPrompt = "You are a skilled translator. Correct any typos in the English while translating it into Spanish, ensuring the translation is accurate and natural."
    const result = await translator.translateText(text, null, targetLang,{context:systemPrompt});
    console.log("Translated text:", result.text);
  } catch (error) {
    console.error("Error during translation:", error.message);
  }
}

// Example usage

console.log(translateText("Hello darkness my old friend Ive come to talk with you again", "ES"));

```

**Comment by JavaPr288** [comment]
Will close the issue!
Removing the context prompt solved the issue.
Thanks again for your help!
