### ISSUE TITLE
autotranslate does not work

### ISSUE THREAD

**Issue by svumme** [DeepLcom/deepl-node#6]
today autotranslate does not work, until yesterday it worked fine, today the language detected is the same as the target language

**Comment by daniel-jones-deepl** [comment]
Hi @svumme, thanks for reporting the issue. Can you please give more information, for example the input you used?

**Comment by daniel-jones-deepl** [comment]
I'm closing this issue as we cannot reproduce it without more information. Feel free to comment again in future.
