### ISSUE TITLE
`.translateText` function overload is not exhaustively typed

### ISSUE THREAD

**Issue by jblossey** [DeepLcom/deepl-node#9]
## Summary

Your definition of `.translateText` runs into [this canonically known typescript issue](https://github.com/microsoft/TypeScript/issues/1805). It expects the language compiler to exhaustively perform a combinatorically expensive type casting which is not supported.

## Code
```typescript
type TranslationText = string | string[];
const firstTextToTranslate: TranslationText = 'hello world';
const secondTextToTranslate: TranslationText = ['hello world'];

deepl.translateText(firstTextToTranslate, ...);
/* yields compiler error:
No overload matches this call.
  Overload 1 of 2, '(texts: string, sourceLang: SourceLanguageCode | null, targetLang: TargetLanguageCode, options?: TranslateTextOptions | undefined): Promise<...>', gave the following error.
    Argument of type 'string | string[]' is not assignable to parameter of type 'string'.
      Type 'string[]' is not assignable to type 'string'.
  Overload 2 of 2, '(texts: string[], sourceLang: SourceLanguageCode | null, targetLang: TargetLanguageCode, options?: TranslateTextOptions | undefined): Promise<...>', gave the following error.
    Argument of type 'string | string[]' is not assignable to parameter of type 'string[]'.
      Type 'string' is not assignable to type 'string[]'.ts(2769)
*/

// on the other hand...
deepl.translateText(secondTextToTranslate, ...);
/* yields the same compiler error: */
```

## Expected Behaviour

Typescript/your type definitions should be able to deduce that your function supports both types of inputs

## Solution Proposition

As the Typescript team already made very clear that they are not planning to implement a combinatorically expensive feature, we have to work around this.

The typescript docs on [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) state that overloading is unnecessary and your function definition could be done in a single, stable go with some generics and conditional types.

```typescript
  async translateText<T extends string | string[]>(
      texts: T,
      sourceLang: SourceLanguageCode | null,
      targetLang: TargetLanguageCode,
      options?: TranslateTextOptions,
  ): Promise<T extends string ? TextResult : TextResult[]>
```

**Comment by daniel-jones-deepl** [comment]
Hi Jannis, thanks for this great suggestion. I'll include your proposal in the next update.
